### ISSUE TITLE
Prototype [24/01/2015]

### ISSUE THREAD

**Issue by Narkan5** [JB-MIAGE/kluh#3]
![prototype_v2](https://cloud.githubusercontent.com/assets/9308741/5887691/f089b7b4-a3df-11e4-9ebb-0efb1be43ee3.png)

**Comment by rachel001** [comment]
Relation d association :entre Membre et   PlanEntrenainement (pas d’agrégat car Membre n’est pas une partie de Entrainement et vice versa)
Relation de composite : entre PlanEntrainement et Entrenement  (car ce dernier est partie du PlanEntrainement et lorsque on supprime un plan d’entrainement on supprime aussi les Entrainement qui le compose) 
Relation de composite :entre Membre et exercice(car si je supprime un membre obligatoirement je dois supprimer ses exercices).
J’ai supprimé la relation  entre  Membre et Entrainement  car Entrainement est fortement couplé au PlanEntrainement qui est en relation avec un Membre 


![mus](https://cloud.githubusercontent.com/assets/10528704/5888573/dd54cdda-a404-11e4-8e64-d1c68b6168a8.PNG)
